services:
  # database containers, one for each db
  db:
    container_name: sc_wgs_db
    build:
      context: .
      dockerfile: monitoring_db.Dockerfile
    image: sc_wgs_monitoring_db:1.0.0
    volumes:
      - db:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - POSTGRES_DB

  # web container, with django + gunicorn
  monitoring:
    container_name: sc_wgs_monitoring
    build:
      context: .
      dockerfile: monitoring_app.Dockerfile
    image: sc_wgs_monitoring:1.0.1
    expose:
      - 8010
    depends_on:
      - db

  # reverse proxy container (nginx)
  nginx:
    container_name: sc_wgs_monitoring_proxy
    image: nginx:1.23
    ports:
      - 8012:80
    volumes:
      - ./config/nginx/conf.d:/etc/nginx/conf.d
      # - volume in the server in which the cron job will for new files
    environment:
      - VIRTUAL_HOST
      - VIRTUAL_PATH
    expose:
      - 8012
    depends_on:
      - monitoring

networks:
  default:
    name: nginx-default
    external: true

volumes:
  db:
    name: sc_wgs_db
