CREATE TABLE "sc_wgs_data" (
  "id" int PRIMARY KEY generated by default as identity,
  "specimen_id" varchar(500),
  "referral_id" varchar(500),
  "date" date,
  "clinical_indication" varchar(500),
  "job_id" varchar(500),
  "job_status" varchar(500),
  "processing_status" varchar(500),
  "workbook_dnanexus_location" varchar(500),
  "workbook_clingen_location" varchar(500)
);
